[build]
  command = "node scripts/build-netlify.js && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://persian-medical-chatbot.netlify.app"
  NEXTAUTH_URL = "https://persian-medical-chatbot.netlify.app"
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[functions]
  included_files = ["prisma/schema.prisma", "prisma/*.sql", "node_modules/.prisma/**", "node_modules/@prisma/client/**"]
  external_node_modules = ["bcryptjs", "@prisma/client", "pg"]
  node_bundler = "esbuild"

# Let the Next.js plugin handle all routing by default
# The plugin will automatically route all requests to the appropriate function

# Only add explicit redirects for the auth paths that are causing issues
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

# The fallback redirect should be simple
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next" 