[build]
  command = "node scripts/build-netlify.js && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://persian-medical-chatbot.netlify.app"
  NEXTAUTH_URL = "https://persian-medical-chatbot.netlify.app"
  # You'll need to set DATABASE_URL in the Netlify UI environment variables
  # DATABASE_URL = "postgresql://username:password@endpoint.neon.tech/database?sslmode=require"
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[functions]
  included_files = ["prisma/schema.prisma", "prisma/*.sql", "node_modules/.prisma/**", "node_modules/@prisma/client/**", "node_modules/pdfjs-dist/**", "node_modules/tesseract.js/**"]
  external_node_modules = ["bcryptjs", "@prisma/client", "pg", "pdfjs-dist", "tesseract.js"]
  node_bundler = "esbuild"

# Define function-specific settings
[[functions]]
  # Apply this to all functions
  pattern = "*"
  # Increase timeouts for OCR operations which can be time-consuming
  included_files = []
  excluded_files = []
  external_node_modules = []
  ignore_package_json_engines = false
  node_bundler = "esbuild"
  timeout = 60

# Let the Next.js plugin handle all routing by default
# The plugin will automatically route all requests to the appropriate function

# Handle NextAuth sign-out redirects explicitly
[[redirects]]
  from = "/api/auth/signout"
  to = "/api/auth/signout"
  status = 200

[[redirects]]
  from = "/api/auth/signout/callback"
  to = "/"
  status = 302
  force = true

# Only add explicit redirects for the auth paths that are causing issues
[[redirects]]
  from = "/auth/*"
  to = "/auth/:splat"
  status = 200

# Handle laboratory uploads explicitly
[[redirects]]
  from = "/api/laboratory/upload"
  to = "/api/laboratory/upload"
  status = 200
  force = true

# The fallback redirect should be simple
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next" 