[build]
  command = "npx prisma generate && npx prisma migrate deploy && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://persian-medical-chatbot.netlify.app"
  NEXTAUTH_URL = "https://persian-medical-chatbot.netlify.app"
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["prisma/schema.prisma", "prisma/*.sql", "node_modules/.prisma/**", "node_modules/@prisma/client/**"]

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next" 