[build]
  command = "node scripts/build-netlify.js && npm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://persian-medical-chatbot.netlify.app"
  NEXTAUTH_URL = "https://persian-medical-chatbot.netlify.app"
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["prisma/schema.prisma", "prisma/*.sql", "node_modules/.prisma/**", "node_modules/@prisma/client/**"]
  external_node_modules = ["bcryptjs", "@prisma/client", "pg"]
  node_bundler = "esbuild"

# Handling _next/static assets
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Handle API routes first
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next-api/:splat"
  status = 200

# Handle the NextAuth default callback route
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/next-api/auth/:splat"
  status = 200

# Handle auth pages explicitly with Next.js
[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/next-server/auth/:splat"
  status = 200
  force = true

# Handle any other routes with Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next-server/:splat"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next" 